function buat_login() {
  var elem = document.getElementById("x");
  elem.parentElement.removeChild(elem);
  var p = document.createElement("p");
  p.className = "tulisan_login";
  p.innerHTML = "SILAHKAN MENDAFTAR";
   var element = document.getElementsByTagName("div")[0];
   element.appendChild(p);
   var form = document.createElement("FORM");
   element.appendChild(form);
   var label = document.createElement("label");
   label.innerHTML = "Nama User";
   form.appendChild(label);
   var input_username = document.createElement("input");
   input_username .type = "text";
   input_username .name = "username";
   input_username.className = "form_login";
   input_username.placeholder = "Nama User..";
   form.appendChild(input_username);
   var labelhp = document.createElement("label");
   labelhp.innerHTML = "Nomor Handphone";
   form.appendChild(labelhp);
   var input_hp = document.createElement("input");
   input_hp .type = "text";
   input_hp .name = "username";
   input_hp.className = "form_login";
   input_hp.placeholder = "Nomor Handphone..";
   form.appendChild(input_hp);
   var labeluser = document.createElement("label");
   labeluser.innerHTML = "Username";
   form.appendChild(labeluser);
   var email = document.createElement("input");
   email .type = "text";
   email .name = "username";
   email.className = "form_login";
   email.placeholder = "Username atau email..";
   form.appendChild(email);

    var label2 = document.createElement("label");
    label2.innerHTML = "Password";
    form.appendChild(label2);
    var input_password = document.createElement("input");
    input_password .type ="text";
    input_password .name ="password";
    input_password.className ="form_login";
    input_password.placeholder ="Password..";
    form.appendChild(input_password);
    var tombol = document.createElement("input");
    tombol .type = "submit";
    tombol.className = "tombol_login";
    tombol. value ="DAFTAR SEKARANG";
    form.appendChild(tombol);
}
